
SUB_DEPTH = ../..

elisso_SOURCES += \
	src/elisso/treemodel.cpp \
	src/elisso/contenttype.cpp \
	src/elisso/main.cpp \
	src/elisso/mainwindow.cpp \
	src/elisso/fileops.cpp \
	src/elisso/folderview.cpp \
	src/elisso/foldertree.cpp \
	src/elisso/fsmodel_gio.cpp \
	src/elisso/populate.cpp \
	src/elisso/previewpane.cpp \
	src/elisso/progressdialog.cpp \
	src/elisso/textentrydialog.cpp \
	src/elisso/thumbnailer.cpp \
	src/elisso/treeviewplus.cpp \
