// Generated by gmmproc 2.50.0 -- DO NOT MODIFY!


#include <gtkmm.h>

#include <gtk/gtk.h>
#include <x-gtk/x-iconview_c.h>
#include <x-gtk/x-iconview_cpp.h>
#include <x-gtk/private/x-iconview_p.h>


/* Copyright 1998-2004 The gtkmm Development Team
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#include <glibmm/vectorutils.h>

#include <gtkmm/adjustment.h>

namespace //anonymous namespace
{

static void proxy_foreach_callback(XGtkIconView* /* icon_view */, GtkTreePath* path, void* data)
{
  typedef Gtk::XIconView::SlotForeach SlotType;
  auto& slot = *static_cast<SlotType*>(data);

  try
  {
    slot(Gtk::TreeModel::Path(path, true));
  }
  catch(...)
  {
    Glib::exception_handlers_invoke();
  }
}

} //anonymous namespace


namespace Gtk
{

void XIconView::unset_model()
{
  xiconview_set_model(gobj(), nullptr);
}

void XIconView::selected_foreach(const SlotForeach& slot)
{
  SlotForeach slot_copy(slot);
  xiconview_selected_foreach(const_cast<XGtkIconView*>(gobj()), &proxy_foreach_callback, &slot_copy);
}

bool XIconView::get_item_at_pos(int x, int y, TreeModel::Path& path, CellRenderer*& cell) const
{
  GtkTreePath* cpath = nullptr;
  GtkCellRenderer* ccell = nullptr;
  bool result = xiconview_get_item_at_pos(const_cast<XGtkIconView*>(gobj()), x, y, &cpath, &ccell);

  path = Glib::wrap(cpath); //Don't take copy because the xiconview_get_item_at_pos documentation says we should free this.
  cell = Glib::wrap(ccell);
  return result;
}

bool XIconView::get_item_at_pos(int x, int y, TreeModel::Path& path) const
{
  GtkTreePath* cpath = nullptr;
  bool result = xiconview_get_item_at_pos(const_cast<XGtkIconView*>(gobj()), x, y, &cpath, nullptr);

  path = Glib::wrap(cpath); //Don't take copy because the xiconview_get_item_at_pos documentation says we should free this.
  return result;
}

bool XIconView::get_item_at_pos(int x, int y, CellRenderer*& cell) const
{
  GtkCellRenderer* ccell = nullptr;
  bool result = xiconview_get_item_at_pos(const_cast<XGtkIconView*>(gobj()), x, y, nullptr, &ccell);

  cell = Glib::wrap(ccell);
  return result;
}

bool XIconView::get_visible_range(TreeModel::Path& start_path, TreeModel::Path& end_path) const
{
  GtkTreePath* cstart_path = nullptr;
  GtkTreePath* cend_path = nullptr;
  bool result = xiconview_get_visible_range(const_cast<XGtkIconView*>(gobj()), &cstart_path, &cend_path);

  start_path = Glib::wrap(cstart_path); //Don't take copy because the xiconview_get_visible_range documentation says we should free this.
  end_path = Glib::wrap(cend_path); //Don't take copy because the xiconview_get_visible_range documentation says we should free this.
  return result;
}


bool XIconView::get_cursor(TreeModel::Path& path, CellRenderer*& cell) const
{
  GtkTreePath* cpath = nullptr;
  GtkCellRenderer* ccell = nullptr;
  bool result = xiconview_get_cursor(const_cast<XGtkIconView*>(gobj()), &cpath, &ccell);

  path = Glib::wrap(cpath); //Don't take copy because the xiconview_get_cursor documentation says we should free this.
  cell = Glib::wrap(ccell);
  return result;
}

bool XIconView::get_cursor(TreeModel::Path& path) const
{
  GtkTreePath* cpath = nullptr;
  bool result = xiconview_get_cursor(const_cast<XGtkIconView*>(gobj()), &cpath, nullptr);

  path = Glib::wrap(cpath); //Don't take copy because the xiconview_get_cursor documentation says we should free this.
  return result;
}

bool XIconView::get_cursor(CellRenderer*& cell) const
{
  GtkCellRenderer* ccell = nullptr;
  bool result = xiconview_get_cursor(const_cast<XGtkIconView*>(gobj()), nullptr, &ccell);

  cell = Glib::wrap(ccell);
  return result;
}

void XIconView::get_drag_dest_item(TreeModel::Path& path, IconViewDropPosition& pos) const
{
  GtkTreePath* cpath = nullptr;
  xiconview_get_drag_dest_item(const_cast<XGtkIconView*>(gobj()), &cpath, (GtkIconViewDropPosition*)(&pos));
  if(cpath)
    path = Gtk::TreeModel::Path(cpath, true /* make_a_copy */);
}

void XIconView::get_drag_dest_item(TreeModel::Path& path) const
{
  GtkTreePath* cpath = nullptr;
  xiconview_get_drag_dest_item(const_cast<XGtkIconView*>(gobj()), &cpath, nullptr);
  if(cpath)
    path = Gtk::TreeModel::Path(cpath, true /* make_a_copy */);
}

void XIconView::get_drag_dest_item(IconViewDropPosition& pos) const
{
   xiconview_get_drag_dest_item(const_cast<XGtkIconView*>(gobj()), nullptr, (GtkIconViewDropPosition*)(&pos));
}


bool XIconView::get_dest_item_at_pos(int drag_x, int drag_y, TreeModel::Path& path, IconViewDropPosition& pos) const
{
  GtkTreePath* cpath = nullptr;
  const bool result = xiconview_get_dest_item_at_pos(const_cast<XGtkIconView*>(gobj()), drag_x, drag_y, &cpath, (GtkIconViewDropPosition*)(&pos));
  if(cpath)
    path = Gtk::TreeModel::Path(cpath, true /* make_a_copy */);

  return result;
}

bool XIconView::get_dest_item_at_pos(int drag_x, int drag_y, TreeModel::Path& path) const
{
  GtkTreePath* cpath = nullptr;
  const bool result = xiconview_get_dest_item_at_pos(const_cast<XGtkIconView*>(gobj()), drag_x, drag_y, &cpath, nullptr);
  if(cpath)
    path = Gtk::TreeModel::Path(cpath, true /* make_a_copy */);

  return result;
}

bool XIconView::get_dest_item_at_pos(int drag_x, int drag_y, IconViewDropPosition& pos) const
{
  return xiconview_get_dest_item_at_pos(const_cast<XGtkIconView*>(gobj()), drag_x, drag_y, nullptr, (GtkIconViewDropPosition*)(&pos));
}


void XIconView::enable_model_drag_source(const std::vector<TargetEntry>& targets, Gdk::ModifierType start_button_mask, Gdk::DragAction actions)
{
  xiconview_enable_model_drag_source(gobj(), (GdkModifierType)start_button_mask, Glib::ArrayHandler<TargetEntry, TargetEntryTraits>::vector_to_array(targets).data (), targets.size(), (GdkDragAction)actions);
}


void  XIconView::enable_model_drag_dest(const std::vector<TargetEntry>& targets, Gdk::DragAction actions)
{
  xiconview_enable_model_drag_dest(gobj(), Glib::ArrayHandler<TargetEntry, TargetEntryTraits>::vector_to_array(targets).data(), targets.size(), (GdkDragAction)actions);
}

bool
XIconView::get_tooltip_context_path(int& x, int& y,
                                   bool keyboard_tip,
                                   TreeModel::Path& path)
{
  GtkTreePath* cpath = nullptr;

  gboolean result =
    xiconview_get_tooltip_context(gobj(),
                                      &x, &y,
                                      keyboard_tip,
                                      nullptr,
                                      &cpath,
                                      nullptr);

  // If result is false, cpath is not modified, it's still 0.
  // wrap() can handle that situation.
  path = Glib::wrap(cpath, /* take_copy= */ false);

  return result;
}

bool
XIconView::get_tooltip_context_iter(int& x, int& y,
                                   bool keyboard_tip,
                                   Gtk::TreeModel::iterator& iter)
{
  GtkTreeIter src_iter;

  gboolean result =
    xiconview_get_tooltip_context(gobj(),
                                      &x, &y,
                                      keyboard_tip,
                                      nullptr,
                                      nullptr,
                                      &src_iter);

  iter = TreeIter(xiconview_get_model(this->gobj()), &src_iter);

  return result;
}

} // namespace Gtk


namespace
{


static void IconView_signal_item_activated_callback(GtkIconView* self, GtkTreePath* p0,void* data)
{
  using namespace Gtk;
  using SlotType = sigc::slot< void,const TreeModel::Path& >;

  auto obj = dynamic_cast<XIconView*>(Glib::ObjectBase::_get_current_wrapper((GObject*) self));
  // Do not try to call a signal on a disassociated wrapper.
  if(obj)
  {
    try
    {
      if(const auto slot = Glib::SignalProxyNormal::data_to_slot(data))
        (*static_cast<SlotType*>(slot))(Gtk::TreePath(p0, true)
);
    }
    catch(...)
    {
       Glib::exception_handlers_invoke();
    }
  }
}

static const Glib::SignalProxyInfo IconView_signal_item_activated_info =
{
  "item_activated",
  (GCallback) &IconView_signal_item_activated_callback,
  (GCallback) &IconView_signal_item_activated_callback
};


static const Glib::SignalProxyInfo IconView_signal_selection_changed_info =
{
  "selection_changed",
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback,
  (GCallback) &Glib::SignalProxyNormal::slot0_void_callback
};


} // anonymous namespace

// static
// GType Glib::Value<Gtk::IconViewDropPosition>::value_type()
// {
//   return xiconview_drop_position_get_type();
// }


namespace Glib
{

Gtk::XIconView* wrap(XGtkIconView* object, bool take_copy)
{
  return dynamic_cast<Gtk::XIconView *> (Glib::wrap_auto ((GObject*)(object), take_copy));
}

} /* namespace Glib */

namespace Gtk
{


/* The *_Class implementation: */

const Glib::Class& XIconView_Class::init()
{
  if(!gtype_) // create the GType if necessary
  {
    // Glib::Class has to know the class init function to clone custom types.
    class_init_func_ = &XIconView_Class::class_init_function;

    // This is actually just optimized away, apparently with no harm.
    // Make sure that the parent type has been created.
    //CppClassParent::CppObjectType::get_type();

    // Create the wrapper type, with the same class/instance size as the base type.
    register_derived_type(xiconview_get_type());

    // Add derived versions of interfaces, if the C type implements any interfaces:
  CellLayout::add_interface(get_type());
  Scrollable::add_interface(get_type());

  }

  return *this;
}


void XIconView_Class::class_init_function(void* g_class, void* class_data)
{
  const auto klass = static_cast<BaseClassType*>(g_class);
  CppClassParent::class_init_function(klass, class_data);


  klass->item_activated = &item_activated_callback;
  klass->selection_changed = &selection_changed_callback;
}


void XIconView_Class::item_activated_callback(XGtkIconView* self, GtkTreePath* p0)
{
  const auto obj_base = static_cast<Glib::ObjectBase*>(
      Glib::ObjectBase::_get_current_wrapper((GObject*)self));

  // Non-gtkmmproc-generated custom classes implicitly call the default
  // Glib::ObjectBase constructor, which sets is_derived_. But gtkmmproc-
  // generated classes can use this optimisation, which avoids the unnecessary
  // parameter conversions if there is no possibility of the virtual function
  // being overridden:
  if(obj_base && obj_base->is_derived_())
  {
    const auto obj = dynamic_cast<CppObjectType* const>(obj_base);
    if(obj) // This can be NULL during destruction.
    {
      try // Trap C++ exceptions which would normally be lost because this is a C callback.
      {
        // Call the virtual member method, which derived classes might override.
        obj->on_item_activated(Gtk::TreePath(p0, true)
);
        return;
      }
      catch(...)
      {
        Glib::exception_handlers_invoke();
      }
    }
  }

  const auto base = static_cast<BaseClassType*>(
        g_type_class_peek_parent(G_OBJECT_GET_CLASS(self)) // Get the parent class of the object class (The original underlying C class).
    );

  // Call the original underlying C function:
  if(base && base->item_activated)
    (*base->item_activated)(self, p0);
}
void XIconView_Class::selection_changed_callback(XGtkIconView* self)
{
  const auto obj_base = static_cast<Glib::ObjectBase*>(
      Glib::ObjectBase::_get_current_wrapper((GObject*)self));

  // Non-gtkmmproc-generated custom classes implicitly call the default
  // Glib::ObjectBase constructor, which sets is_derived_. But gtkmmproc-
  // generated classes can use this optimisation, which avoids the unnecessary
  // parameter conversions if there is no possibility of the virtual function
  // being overridden:
  if(obj_base && obj_base->is_derived_())
  {
    const auto obj = dynamic_cast<CppObjectType* const>(obj_base);
    if(obj) // This can be NULL during destruction.
    {
      try // Trap C++ exceptions which would normally be lost because this is a C callback.
      {
        // Call the virtual member method, which derived classes might override.
        obj->on_selection_changed();
        return;
      }
      catch(...)
      {
        Glib::exception_handlers_invoke();
      }
    }
  }

  const auto base = static_cast<BaseClassType*>(
        g_type_class_peek_parent(G_OBJECT_GET_CLASS(self)) // Get the parent class of the object class (The original underlying C class).
    );

  // Call the original underlying C function:
  if(base && base->selection_changed)
    (*base->selection_changed)(self);
}


Glib::ObjectBase* XIconView_Class::wrap_new(GObject* o)
{
  return manage(new XIconView((XGtkIconView*)(o)));

}


/* The implementation: */

XIconView::XIconView(const Glib::ConstructParams& construct_params)
:
  Gtk::Container(construct_params)
{
  }

XIconView::XIconView(XGtkIconView* castitem)
:
  Gtk::Container((GtkContainer*)(castitem))
{
  }


XIconView::XIconView(XIconView&& src) noexcept
: Gtk::Container(std::move(src))
  , CellLayout(std::move(src))
  , Scrollable(std::move(src))
{}

XIconView& XIconView::operator=(XIconView&& src) noexcept
{
  Gtk::Container::operator=(std::move(src));
  CellLayout::operator=(std::move(src));
  Scrollable::operator=(std::move(src));
  return *this;
}

XIconView::~XIconView() noexcept
{
  destroy_();
}

XIconView::CppClassType XIconView::xiconview_class_; // initialize static member

GType XIconView::get_type()
{
  return xiconview_class_.init().get_type();
}


GType XIconView::get_base_type()
{
  return xiconview_get_type();
}


XIconView::XIconView()
:
  // Mark this class as non-derived to allow C++ vfuncs to be skipped.
  Glib::ObjectBase(nullptr),
  Gtk::Container(Glib::ConstructParams(xiconview_class_.init()))
{


}

XIconView::XIconView(const Glib::RefPtr<TreeModel>& model)
:
  // Mark this class as non-derived to allow C++ vfuncs to be skipped.
  Glib::ObjectBase(nullptr),
  Gtk::Container(Glib::ConstructParams(xiconview_class_.init(), "model", Glib::unwrap(model), nullptr))
{


}

XIconView::XIconView(const Glib::RefPtr<CellArea>& cell_area)
:
  // Mark this class as non-derived to allow C++ vfuncs to be skipped.
  Glib::ObjectBase(nullptr),
  Gtk::Container(Glib::ConstructParams(xiconview_class_.init(), "cell_area", Glib::unwrap(cell_area), nullptr))
{


}

void XIconView::set_model(const Glib::RefPtr<TreeModel>& model)
{
  xiconview_set_model(gobj(), Glib::unwrap(model));
}

Glib::RefPtr<TreeModel> XIconView::get_model()
{
  Glib::RefPtr<TreeModel> retvalue = Glib::wrap(xiconview_get_model(gobj()));
  if(retvalue)
    retvalue->reference(); //The function does not do a ref for us.
  return retvalue;
}

Glib::RefPtr<const TreeModel> XIconView::get_model() const
{
  return const_cast<XIconView*>(this)->get_model();
}

void XIconView::set_text_column(int column)
{
  xiconview_set_text_column(gobj(), column);
}

void XIconView::set_text_column(const TreeModelColumnBase& model_column)
{
  xiconview_set_text_column(gobj(), (model_column).index());
}

int XIconView::get_text_column() const
{
  return xiconview_get_text_column(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_markup_column(int column)
{
  xiconview_set_markup_column(gobj(), column);
}

void XIconView::set_markup_column(const TreeModelColumnBase& column)
{
  xiconview_set_markup_column(gobj(), (column).index());
}

int XIconView::get_markup_column() const
{
  return xiconview_get_markup_column(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_pixbuf_column(int column)
{
  xiconview_set_pixbuf_column(gobj(), column);
}

void XIconView::set_pixbuf_column(const TreeModelColumnBase& column)
{
  xiconview_set_pixbuf_column(gobj(), (column).index());
}

int XIconView::get_pixbuf_column() const
{
  return xiconview_get_pixbuf_column(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_item_orientation(Orientation orientation)
{
  xiconview_set_item_orientation(gobj(), ((GtkOrientation)(orientation)));
}

Orientation XIconView::get_item_orientation() const
{
  return ((Orientation)(xiconview_get_item_orientation(const_cast<XGtkIconView*>(gobj()))));
}

void XIconView::set_columns(int columns)
{
  xiconview_set_columns(gobj(), columns);
}

int XIconView::get_columns() const
{
  return xiconview_get_columns(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_item_width(int item_width)
{
  xiconview_set_item_width(gobj(), item_width);
}

int XIconView::get_icon_width() const
{
  return xiconview_get_item_width(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_spacing(int spacing)
{
  xiconview_set_spacing(gobj(), spacing);
}

int XIconView::get_spacing() const
{
  return xiconview_get_spacing(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_row_spacing(int row_spacing)
{
  xiconview_set_row_spacing(gobj(), row_spacing);
}

gint XIconView::get_row_spacing() const
{
  return xiconview_get_row_spacing(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_column_spacing(int column_spacing)
{
  xiconview_set_column_spacing(gobj(), column_spacing);
}

int XIconView::get_column_spacing() const
{
  return xiconview_get_column_spacing(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_margin(int margin)
{
  xiconview_set_margin(gobj(), margin);
}

int XIconView::get_margin() const
{
  return xiconview_get_margin(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_item_padding(int item_padding)
{
  xiconview_set_item_padding(gobj(), item_padding);
}

int XIconView::get_item_padding() const
{
  return xiconview_get_item_padding(const_cast<XGtkIconView*>(gobj()));
}

TreeModel::Path XIconView::get_path_at_pos(int x, int y) const
{
  return Gtk::TreePath(xiconview_get_path_at_pos(const_cast<XGtkIconView*>(gobj()), x, y), false);
}

void XIconView::set_activate_on_single_click(bool single)
{
  xiconview_set_activate_on_single_click(gobj(), static_cast<int>(single));
}

bool XIconView::get_activate_on_single_click() const
{
  return xiconview_get_activate_on_single_click(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_selection_mode(SelectionMode mode)
{
  xiconview_set_selection_mode(gobj(), ((GtkSelectionMode)(mode)));
}

SelectionMode XIconView::get_selection_mode() const
{
  return ((SelectionMode)(xiconview_get_selection_mode(const_cast<XGtkIconView*>(gobj()))));
}

void XIconView::select_path(const TreeModel::Path& path)
{
  xiconview_select_path(gobj(), const_cast<GtkTreePath*>((path).gobj()));
}

void XIconView::unselect_path(const TreeModel::Path& path)
{
  xiconview_unselect_path(gobj(), const_cast<GtkTreePath*>((path).gobj()));
}

bool XIconView::path_is_selected(const TreeModel::Path& path) const
{
  return xiconview_path_is_selected(const_cast<XGtkIconView*>(gobj()), const_cast<GtkTreePath*>((path).gobj()));
}

int XIconView::get_item_row(const TreeModel::Path& path) const
{
  return xiconview_get_item_row(const_cast<XGtkIconView*>(gobj()), const_cast<GtkTreePath*>((path).gobj()));
}

int XIconView::get_item_column(const TreeModel::Path& path) const
{
  return xiconview_get_item_column(const_cast<XGtkIconView*>(gobj()), const_cast<GtkTreePath*>((path).gobj()));
}

std::vector<TreePath> XIconView::get_selected_items() const
{
  return Glib::ListHandler<TreePath, TreePathTraits>::list_to_vector(xiconview_get_selected_items(const_cast<XGtkIconView*>(gobj())), Glib::OWNERSHIP_SHALLOW);
}

void XIconView::select_all()
{
  xiconview_select_all(gobj());
}

void XIconView::unselect_all()
{
  xiconview_unselect_all(gobj());
}

void XIconView::item_activated(const TreeModel::Path& path)
{
  xiconview_item_activated(gobj(), const_cast<GtkTreePath*>((path).gobj()));
}

void XIconView::set_cursor(const TreeModel::Path& path, CellRenderer& cell, bool start_editing)
{
  xiconview_set_cursor(gobj(), const_cast<GtkTreePath*>((path).gobj()), (cell).gobj(), static_cast<int>(start_editing));
}

void XIconView::set_cursor(const TreeModel::Path& path, bool start_editing)
{
  xiconview_set_cursor(gobj(), const_cast<GtkTreePath*>((path).gobj()), nullptr, static_cast<int>(start_editing));
}

void XIconView::scroll_to_path(const TreeModel::Path& path, bool use_align, gfloat row_align, gfloat col_align)
{
  xiconview_scroll_to_path(gobj(), const_cast<GtkTreePath*>((path).gobj()), static_cast<int>(use_align), row_align, col_align);
}

void XIconView::unset_model_drag_source()
{
  xiconview_unset_model_drag_source(gobj());
}

void XIconView::unset_model_drag_dest()
{
  xiconview_unset_model_drag_dest(gobj());
}

void XIconView::set_reorderable(bool reorderable)
{
  xiconview_set_reorderable(gobj(), static_cast<int>(reorderable));
}

bool XIconView::get_reorderable() const
{
  return xiconview_get_reorderable(const_cast<XGtkIconView*>(gobj()));
}

void XIconView::set_drag_dest_item(const TreeModel::Path& path, IconViewDropPosition pos)
{
  xiconview_set_drag_dest_item(gobj(), const_cast<GtkTreePath*>((path).gobj()), ((GtkIconViewDropPosition)(pos)));
}

Cairo::RefPtr<Cairo::Surface> XIconView::create_drag_icon(const TreeModel::Path& path)
{
  return Cairo::RefPtr<Cairo::Surface>(new Cairo::Surface(xiconview_create_drag_icon(gobj(), const_cast<GtkTreePath*>((path).gobj())), false /* take reference */));
}

void XIconView::convert_widget_to_bin_window_coords(int wx, int wy, int& bx, int& by) const
{
  xiconview_convert_widget_to_bin_window_coords(const_cast<XGtkIconView*>(gobj()), wx, wy, &(bx), &(by));
}

bool XIconView::get_cell_rect(const TreeModel::Path& path, const CellRenderer& cell, Gdk::Rectangle& rect) const
{
  GdkRectangle g_rect = GdkRectangle();
  bool retvalue = xiconview_get_cell_rect(const_cast<XGtkIconView*>(gobj()), const_cast<GtkTreePath*>((path).gobj()), const_cast<GtkCellRenderer*>((cell).gobj()), &g_rect);
rect = Glib::wrap(&(g_rect));
  return retvalue;
}

bool XIconView::get_cell_rect(const TreeModel::Path& path, Gdk::Rectangle& rect) const
{
  GdkRectangle g_rect = GdkRectangle();
  bool retvalue = xiconview_get_cell_rect(const_cast<XGtkIconView*>(gobj()), const_cast<GtkTreePath*>((path).gobj()), nullptr, &g_rect);
rect = Glib::wrap(&(g_rect));
  return retvalue;
}

void XIconView::set_tooltip_item(const Glib::RefPtr<Tooltip>& tooltip, const TreeModel::Path& path)
{
  xiconview_set_tooltip_item(gobj(), Glib::unwrap(tooltip), const_cast<GtkTreePath*>((path).gobj()));
}

void XIconView::set_tooltip_cell(const Glib::RefPtr<Tooltip>& tooltip, const TreeModel::Path& path, CellRenderer& cell)
{
  xiconview_set_tooltip_cell(gobj(), Glib::unwrap(tooltip), const_cast<GtkTreePath*>((path).gobj()), (cell).gobj());
}

void XIconView::set_tooltip_column(int column)
{
  xiconview_set_tooltip_column(gobj(), column);
}

int XIconView::get_tooltip_column() const
{
  return xiconview_get_tooltip_column(const_cast<XGtkIconView*>(gobj()));
}


Glib::SignalProxy< void,const TreeModel::Path& > XIconView::signal_item_activated()
{
  return Glib::SignalProxy< void,const TreeModel::Path& >(this, &IconView_signal_item_activated_info);
}


Glib::SignalProxy< void > XIconView::signal_selection_changed()
{
  return Glib::SignalProxy< void >(this, &IconView_signal_selection_changed_info);
}


Glib::PropertyProxy< int > XIconView::property_pixbuf_column()
{
  return Glib::PropertyProxy< int >(this, "pixbuf-column");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_pixbuf_column() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "pixbuf-column");
}

Glib::PropertyProxy< int > XIconView::property_text_column()
{
  return Glib::PropertyProxy< int >(this, "text-column");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_text_column() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "text-column");
}

Glib::PropertyProxy< int > XIconView::property_markup_column()
{
  return Glib::PropertyProxy< int >(this, "markup-column");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_markup_column() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "markup-column");
}

Glib::PropertyProxy< SelectionMode > XIconView::property_selection_mode()
{
  return Glib::PropertyProxy< SelectionMode >(this, "selection-mode");
}

Glib::PropertyProxy_ReadOnly< SelectionMode > XIconView::property_selection_mode() const
{
  return Glib::PropertyProxy_ReadOnly< SelectionMode >(this, "selection-mode");
}

Glib::PropertyProxy< Orientation > XIconView::property_item_orientation()
{
  return Glib::PropertyProxy< Orientation >(this, "item-orientation");
}

Glib::PropertyProxy_ReadOnly< Orientation > XIconView::property_item_orientation() const
{
  return Glib::PropertyProxy_ReadOnly< Orientation >(this, "item-orientation");
}

Glib::PropertyProxy< Glib::RefPtr<TreeModel> > XIconView::property_model()
{
  return Glib::PropertyProxy< Glib::RefPtr<TreeModel> >(this, "model");
}

Glib::PropertyProxy_ReadOnly< Glib::RefPtr<TreeModel> > XIconView::property_model() const
{
  return Glib::PropertyProxy_ReadOnly< Glib::RefPtr<TreeModel> >(this, "model");
}

Glib::PropertyProxy< int > XIconView::property_columns()
{
  return Glib::PropertyProxy< int >(this, "columns");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_columns() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "columns");
}

Glib::PropertyProxy< int > XIconView::property_item_width()
{
  return Glib::PropertyProxy< int >(this, "item-width");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_item_width() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "item-width");
}

Glib::PropertyProxy< int > XIconView::property_spacing()
{
  return Glib::PropertyProxy< int >(this, "spacing");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_spacing() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "spacing");
}

Glib::PropertyProxy< int > XIconView::property_row_spacing()
{
  return Glib::PropertyProxy< int >(this, "row-spacing");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_row_spacing() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "row-spacing");
}

Glib::PropertyProxy< int > XIconView::property_column_spacing()
{
  return Glib::PropertyProxy< int >(this, "column-spacing");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_column_spacing() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "column-spacing");
}

Glib::PropertyProxy< int > XIconView::property_margin()
{
  return Glib::PropertyProxy< int >(this, "margin");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_margin() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "margin");
}

Glib::PropertyProxy< int > XIconView::property_reorderable()
{
  return Glib::PropertyProxy< int >(this, "reorderable");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_reorderable() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "reorderable");
}

Glib::PropertyProxy< int > XIconView::property_tooltip_column()
{
  return Glib::PropertyProxy< int >(this, "tooltip-column");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_tooltip_column() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "tooltip-column");
}

Glib::PropertyProxy< int > XIconView::property_item_padding()
{
  return Glib::PropertyProxy< int >(this, "item-padding");
}

Glib::PropertyProxy_ReadOnly< int > XIconView::property_item_padding() const
{
  return Glib::PropertyProxy_ReadOnly< int >(this, "item-padding");
}

Glib::PropertyProxy_ReadOnly< Glib::RefPtr<CellArea> > XIconView::property_cell_area() const
{
  return Glib::PropertyProxy_ReadOnly< Glib::RefPtr<CellArea> >(this, "cell-area");
}

Glib::PropertyProxy< bool > XIconView::property_activate_on_single_click()
{
  return Glib::PropertyProxy< bool >(this, "activate-on-single-click");
}

Glib::PropertyProxy_ReadOnly< bool > XIconView::property_activate_on_single_click() const
{
  return Glib::PropertyProxy_ReadOnly< bool >(this, "activate-on-single-click");
}


void Gtk::XIconView::on_item_activated(const TreeModel::Path& path)
{
  const auto base = static_cast<BaseClassType*>(
      g_type_class_peek_parent(G_OBJECT_GET_CLASS(gobject_)) // Get the parent class of the object class (The original underlying C class).
  );

  if(base && base->item_activated)
    (*base->item_activated)(gobj(),const_cast<GtkTreePath*>((path).gobj()));
}
void Gtk::XIconView::on_selection_changed()
{
  const auto base = static_cast<BaseClassType*>(
      g_type_class_peek_parent(G_OBJECT_GET_CLASS(gobject_)) // Get the parent class of the object class (The original underlying C class).
  );

  if(base && base->selection_changed)
    (*base->selection_changed)(gobj());
}


} // namespace Gtk


